# Generated by Django 4.2.4 on 2023-08-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_recipe_meal_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='picture',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
