# Generated by Django 4.2.4 on 2023-08-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_meal_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
    ]
