# Generated by Django 4.2.4 on 2023-08-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_name_ingredient_item_remove_meal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
