# Generated by Django 3.2.12 on 2023-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_meal_ingredients_alter_meal_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
